import { Button, VerticalBox, LineEdit } from "std-widgets.slint";

export component AppWindow inherits Window 
{
    background: #313e50;
    GridLayout 
    {
        
        
        padding: 50px;
        spacing: 25px;
        Row
        {
            Text
            {
                text: "Enter total income";
                horizontal-alignment: center;
                font-size: 24px;
                font-weight: 900;
            }
        }
        Row
        {
            LineEdit 
            {
                horizontal-alignment: center;
                font-size: 16px;
                placeholder-text: "Enter your number";
            }
        }
        Row
        {
            Button 
            {
                text: "Calculate";
                primary: true;
            }
        }
    }
}

// creating a grid layout for table like GUI
// do 3 lines - 3 rows
// adjust the GUI window - horizontal center alignment, make the font 24, and the font weight 900
// Adding the text box through line edit with a "enter number" request" with 16 pixels and 16 pixels, horizontal center alignment
// Adding the button
// padding (50) and spacing (25)