import { Button, VerticalBox } from "std-widgets.slint";

export component AppWindow inherits Window 
{
    GridLayout 
    {
        Row
        {
            Text
            {
                text: "Enter total income";
                horizontal-alignment: center;
                font-size: 24px;
                font-weight: 900;
            }
        }
        Row
        {}
        Row
        {}
    }
}
